name: Build one configuration

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      image:
        required: false
        type: string
        default: ""
      compiler:
        required: false
        type: string
        default: ""
      compiler_path:
        required: false
        type: string
        default: ""
      cxxstd:
        required: false
        type: string
        default: "20"
      default:
        required: false
        type: boolean
        default: false

jobs:

  build:
    name: Spack build (${{ inputs.compiler }})
    runs-on: "${{ inputs.os }}"

    outputs:
      target_arch: ${{ steps.lockfile_bookkeeping.outputs.TARGET_ARCH }}
      target_triplet: ${{ steps.lockfile_bookkeeping.outputs.TARGET_TRIPLET }}
      target_triplet_slug: ${{ steps.lockfile_bookkeeping.outputs.TARGET_TRIPLET_SLUG }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Set up Spack
        uses: spack/setup-spack@v2

      - name: Apply spack patches
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -d spack_patches ] && ls spack_patches/*.patch >/dev/null 2>&1; then
            for f in spack_patches/*.patch; do
              git -C spack am -3 "$f"
            done
          fi

      - name: Remove packages to save disk
        run: |
          df -h
          sudo apt-get update
          echo "Removing large packages"
          ci/uninstall_packages.py
          df -h

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Run spack build (container)
        run: |
          docker run \
            -v"$PWD:/src" \
            -v"$(spack location -r):/spack" \
            -v "$GITHUB_ENV:/github_env"\
            -e "SPACK_ROOT=/spack" \
            -e "COMPILER=${{ inputs.compiler }}" \
            -e "COMPILER_PATH=${{ inputs.compiler_path }}" \
            -e "CXXSTD=${{ inputs.cxxstd }}" \
            -e "GH_OCI_USER=${{ github.actor }}" \
            -e "GH_OCI_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            -e "GITHUB_ENV=/github_env" \
            -e "GITHUB_ACTIONS=${GITHUB_ACTIONS}" \
            -w /src \
            ${{ inputs.image }} \
            /src/ci/spack_build.sh

      - name: Lockfile bookkeeping
        shell: bash
        if: always()
        id: lockfile_bookkeeping
        run: |
          cp spack.lock "spack_${TARGET_TRIPLET}.lock"
          if [[ "${{ inputs.default }}" == "true" ]]; then
            # this will be become the default combination for this architecture
            cp spack.lock "spack_${TARGET_ARCH}.lock"
          fi
          echo "TARGET_TRIPLET=${TARGET_TRIPLET}" >> "$GITHUB_OUTPUT"
          echo "TARGET_ARCH=${TARGET_ARCH}" >> "$GITHUB_OUTPUT"
          echo "TARGET_TRIPLET_SLUG=${TARGET_TRIPLET}" | sed 's/@/-/g' >> "$GITHUB_OUTPUT"

      - name: Derive base image
        shell: bash
        if: "!cancelled()"
        run: |
          echo BASE_IMAGE="${{ inputs.image }}" >> "$GITHUB_ENV"

      - name: Print base image
        shell: bash
        if: "!cancelled()"
        run: |
          echo "BASE IMAGE: ${BASE_IMAGE}"

      - name: Create Dockerfile from spack lockfile
        if: "!cancelled()"
        run: |
          uv run lockfile_to_docker.py \
            "spack_${TARGET_TRIPLET}.lock" \
            --base-image ${BASE_IMAGE} \
            --oci-url ghcr.io/opendatadetector/sw \
            -o Dockerfile.${TARGET_TRIPLET}

      - name: Upload lock files and Dockerfiles
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: spack_${{ env.TARGET_TRIPLET }}-locks
          path: |
            spack_*.lock
            Dockerfile.*
          if-no-files-found: error

      - name: Add lock files and Dockerfiles to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            Dockerfile.*
            spack_*.lock

      - name: Push spack cache (container)
        if: "!cancelled()"
        run: |
          docker run \
            -v"$PWD:/src" \
            -v"$(spack location -r):/spack" \
            -e "SPACK_ROOT=/spack" \
            -e "GITHUB_ACTIONS=${GITHUB_ACTIONS}" \
            -e "GH_OCI_USER=${{ github.actor }}" \
            -e "GH_OCI_TOKEN=${{ secrets.GITHUB_TOKEN }}" \
            -e "BASE_IMAGE=${BASE_IMAGE}" \
            -w /src \
            ${{ inputs.image }} \
            /src/ci/spack_push.sh

  build_docker:
    name: Build and push Docker image
    runs-on: "${{ inputs.os }}"
    needs: [build]

    env:
      TARGET_ARCH: ${{ needs.build.outputs.target_arch }}
      TARGET_TRIPLET: ${{ needs.build.outputs.target_triplet }}
      TARGET_TRIPLET_SLUG: ${{ needs.build.outputs.target_triplet_slug }}

    steps:
      - uses: actions/checkout@v6

      - name: Remove packages to save disk
        run: |
          df -h
          sudo apt-get update
          echo "Removing large packages"
          ci/uninstall_packages.py
          df -h

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v7
        with:
          name: spack_${{ env.TARGET_TRIPLET }}-locks

      - run: |
          cp Dockerfile.* Dockerfile

      - uses: docker/login-action@v3
        if: "!cancelled()"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        if: "!cancelled()"
        uses: docker/metadata-action@v5
        id: meta
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/sw
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}_${{ env.TARGET_TRIPLET_SLUG }}
            type=semver,pattern={{major}}.{{minor}}_${{ env.TARGET_TRIPLET_SLUG }}
            type=semver,pattern={{major}}_${{ env.TARGET_TRIPLET_SLUG }}

      - name: Build and push
        if: "!cancelled()"
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
