name: Build dependencies

on:
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "5 4 * * *"

jobs:
  build_container:

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:

        include:
          - os: ubuntu-24.04
          - os: ubuntu-24.04-arm

    uses: ./.github/workflows/build_one.yml
    with:
      os: ${{ matrix.os }}

    secrets: inherit
